# Generated by Django 3.2.6 on 2021-08-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='section_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_involved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_involved', models.CharField(max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_person_involved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_person_involved', models.CharField(max_length=190, null=True)),
            ],
        ),
    ]
