# Generated by Django 3.2.6 on 2021-08-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Damage_level', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Major', 'Major'), ('Catastrophic', 'Catastrophic')], max_length=200, null=True)),
                ('Section_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ovrapp.section_list')),
                ('Type_of_involved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ovrapp.type_of_involved')),
                ('Type_of_person_involved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ovrapp.type_of_person_involved')),
            ],
        ),
    ]
