# Generated by Django 3.2.6 on 2021-08-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovrapp', '0003_auto_20210813_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Section_list',
        ),
    ]
