# Generated by Django 3.2.6 on 2021-08-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovrapp', '0004_remove_order_section_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Event_Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ovrapp.section_list'),
        ),
        migrations.AddField(
            model_name='order',
            name='Reporting_Department_Section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reporting_Department_Section', to='ovrapp.section_list'),
        ),
    ]
